FROM golang:1.27-bookworm

ARG AIR_VERSION=v1.67.3

RUN go install github.com/air-verse/air@${AIR_VERSION}

WORKDIR /workspace

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
